### GET request to example server
GET http://localhost:8080/api/get-accounts?mobilePhone=0868976172

### GET request to example server - fail validate
GET http://localhost:8080/api/get-accounts?mobilePhone=086897617