### DELETE request to delete loan by mobile phone - success
DELETE http://localhost:8082/api/loans?mobilePhone=1234567899

### DELETE request to delete loan by mobile phone - fail
DELETE http://localhost:8082/api/loans?mobilePhone=1234567893


